# Generated by Django 5.0.6 on 2026-07-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPhase',
            fields=[
                ('phase_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('guidance_message', models.TextField(blank=True)),
                ('suggested_questions', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'tbl_school_phase',
                'ordering': ['start_date'],
            },
        ),
    ]
