# Generated by Django 5.0.6 on 2026-09-13 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
        ('tickets', '0002_ticket_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='offices.office'),
        ),
    ]
