# Generated by Django 5.0.6 on 2026-07-10 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_message', models.TextField()),
                ('detected_intent', models.CharField(max_length=100)),
                ('chatbot_response', models.TextField()),
                ('is_escalated', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_inquiry_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
