# Generated by Django 5.0.6 on 2026-09-13 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_logs', '0001_initial'),
        ('offices', '0002_seed_offices'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquirylog',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_logs', to='offices.office'),
        ),
    ]
