# Generated by Django 5.0.6 on 2026-07-10 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('faq_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('intent_keyword', models.CharField(max_length=100)),
                ('question_text', models.TextField()),
                ('answer_content', models.TextField()),
                ('category', models.CharField(choices=[('Enrollment', 'Enrollment'), ('Scholarship', 'Scholarship'), ('Clearance', 'Clearance'), ('Discipline', 'Discipline'), ('General', 'General')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_faqs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_faqs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_faqs',
            },
        ),
    ]
