# Generated by Django 5.0.6 on 2026-08-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='intent_keyword',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
