# Generated by Django 5.0.6 on 2026-09-13 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_alter_faq_intent_keyword'),
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='offices.office'),
        ),
    ]
