# Generated by Django 5.0.6 on 2026-07-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
