# Generated by Django 5.0.6 on 2026-08-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, choices=[('BSIT', 'BS Information Technology'), ('BSCS', 'BS Computer Science'), ('BSDS', 'BS Data Science'), ('BTCM', 'Bachelor in Technology Communication Management'), ('BSARCH', 'BS Architecture'), ('BSCE', 'BS Civil Engineering'), ('BSCPE', 'BS Computer Engineering'), ('BSEE', 'BS Electrical Engineering'), ('BSECE', 'BS Electronics Engineering'), ('BSGE', 'BS Geodetic Engineering'), ('BSME', 'BS Mechanical Engineering'), ('BSAUTO', 'BS Autotronics'), ('BSEMT', 'BS Electro-Mechanical Technology'), ('BSELT', 'BS Electronics Technology'), ('BSESM', 'BS Energy Systems and Management'), ('BSMFG', 'BS Manufacturing Engineering Technology'), ('BTOM', 'Bachelor of Technology, Operations, and Management'), ('BTLED', 'Bachelor in Technology and Livelihood Education'), ('BTVTED', 'Bachelor in Technical-Vocational Teacher Education'), ('BSED', 'BS Secondary Education'), ('BEED', 'BS Elementary Education'), ('BSN', 'BS Nursing'), ('BSBA', 'BS Business Administration'), ('BSA', 'BS Accountancy')], max_length=10, null=True),
        ),
    ]
