# Generated by Django 5.0.6 on 2026-09-13 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def rename_admin_role_to_superadmin(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(role='admin').update(role='superadmin')


def rename_superadmin_role_to_admin(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(role='superadmin').update(role='admin')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('superadmin', 'Super Admin')], default='student', max_length=10),
        ),
        migrations.RunPython(rename_admin_role_to_superadmin, rename_superadmin_role_to_admin),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_email_verification_token',
            },
        ),
    ]
