# Generated by Django 5.0.6 on 2026-09-13 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_seed_offices'),
        ('users', '0007_user_is_email_verified_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='offices.office'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('superadmin', 'Super Admin'), ('office_admin', 'Office Admin')], default='student', max_length=12),
        ),
    ]
